#!/usr/bin/perl
delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};
$ENV{'PATH'}='/bin:/usr/bin:/sbin:/usr/sbin/';

get_dev_param();
get_br_param();
exit 0;

sub get_dev_param() {
    open(FH, "cat /var/log/dmesg |");
    while(<FH>) {
        chomp;
        if ($_ =~ /(eth[0-9])/) {
            $dev_name = $1;
            $hardware = $';
            if(/(\w+\:\w+\:\w+\:\w+:\w+:\w+)/) {
                $mac = $1;
            }
            if ($mac ne "") {
                print "\"dev_name\":\"$dev_name\",";
                $mac =~ s/:/-/g;
                print "\"mac\":\"$mac\",";
                $hardware =~ /:\s(.*),/;
                $hardware = $1;
                $hardware =~ s/:/-/g;
                print "\"hardware\":\"$hardware\",";
            }

            $mac = "";
        }
    }
    close(FH);
}
sub get_br_param() {
    $flag = 0;

    open(FH, "brctl show |");
    while(<FH>) {
        chomp;
        if ($_ =~ /(^.*br[0-9])/) {
            if ($flag) {
                print "\"link_hw\":\"";
                print join('\\', @hw);
                print "\",";
                undef(@hw);
            }
            $link_br = $1;
            @per = split(/\s/); 
            $link_hw = pop @per;
            push @hw, $link_hw; 
            print "\"link_br\":\"$link_br\",";
            $flag = 1;
        } else {
            if ($flag) {
                $_ =~ s/^\s+//;
                push @hw, $_;
            }
        }
    }
    print "\"link_hw\":";
    print join('\\', @hw);
    print "\"";
    close(FH);
}
