#!/usr/bin/perl
delete @ENV{qw(IFS CDPATH ENV BASH_ENV)};
$ENV{'PATH'}='/bin:/usr/bin:/sbin:/usr/sbin/';

get_dev_param();
get_br_param();
exit 0;

sub get_dev_param() {
    open(FH, "cat /var/log/dmesg |");
    while(<FH>) {
        chomp;
        if ($_ =~ /(eth[0-9])/) {
            $dev_name = $1;
            $hardware = $';
            if(/(\w+\:\w+\:\w+\:\w+:\w+:\w+)/) {
                $mac = $1;
            }
            if($mac ne "") {
                print "dev_name=$dev_name\n";
                $mac =~ s/:/-/g;
                print "mac=$mac\n";
                $hardware =~ /:\s(.*),/;
                $hardware = $1;
                $hardware =~ s/:/-/g;
                print "hardware=$hardware\n";
            }

            $mac = "";
        }
    }
    close(FH);
}

